version: "3.6"
services:
  database: 
    build: ./database/postgresql
    ports:
      - 5432:5432
    networks:
      guess-network:
        aliases:
          - guess-database
  auth:
    build: ./auth
    ports: 
      - 10000:8080
      - 10443:8443
    networks:
      guess-network:
        aliases:
          - guess-auth
  admin:
    build: ./java/guess-who-admin
    ports:
      - 5001:5001
    depends_on:
      - database
      - auth
    networks:
      guess-network:
        aliases:
          - guess-admin
networks:
  guess-network:
    driver: bridge
