version: "3.6"
services:
  database: 
    build: ./database/postgresql
    ports:
      - 5432:5432
    networks:
      guess-network:
        aliases:
          - guess-database
  auth:
    build: ./auth
    ports: 
      - 8080:8080
      - 8443:8443
    networks:
      guess-network:
        aliases:
          - guess-auth
  admin-server:
    build: ./java/guess-who-admin
    ports:
      - 5001:5001
    depends_on:
      - database
      - auth
    networks:
      guess-network:
        aliases:
          - guess-admin-server
  admin-client:
    build: ./angular/guess-who-admin
    ports:
      - 8081:80
    depends_on:
      - admin-server
    networks:
      guess-network:
        aliases:
          - guess-admin-client
networks:
  guess-network:
    driver: bridge
